type Staff @model {
  SID: ID
  FirstName: String
  LastName: String
  MobileNumber: Int
  HomeTelephone: Int
  Email: String
  Address: String
  City: String
  Country: String
  Postcode: String
  EmergencyContactName: String
  EmergencyContactNumber: Int
  JobName: String
  JobSalery: String
  JobHours: String
  PracticeName: String
  TypeOfPractice: String
  PracticeAddress: String
  PracticeCity: String
  PracticeCountry: String
  PracticePostcode: String
  PracticeEmail: String
  PracticePhoneNumber: Int
  id: String
}
